### PR TITLE
Explication of how to get notifications added to README

### PR DESCRIPTION
**Pull request by miallo**

### CODE REVIEW

**Comment by markusvoelter** [comment]
Are you sure this works for commits? The docs say: "When you watch a repository, you get notifications for any new pull requests and issues that are created, including those not mentioning you.".

**Comment by miallo** [comment]
Oh, right... Then I got another (not that nice) solution:

Go to the commit-tab and then subscribe to the RSS-feed (in Safari for example klick on the share-button in the top right, then choose Add Website to Shared Links. Then all commits appear in the sidebar under the "@"-tab)

**Comment by derTimme** [comment]
I tried to follow your steps with Firefox and I couldn't find the RSS feed you mentioned. Could you please provide a (series of) screenshot(s) showing what you meant?
Would be great to have such a feed!

**Comment by miallo** [comment]
In Safari it just worked without providing an extra link. While googling I found, that https://github.com/omegataupodcast/episode-prep/commits/master.atom should work with an rss reader of your choice...

**Comment by derTimme** [comment]
You're absolutely right, that seems to work. Thank you!

**Pull request merged**
